Expose THECOLORS to color.py
Expose THECOLORS to color.py, since some games use pygame.color.THECOLORS and pygame exposes THECOLORS in the same way:
pygame_cffi:
>>> pygame.color.THECOLORS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'THECOLORS'

pygame:
>>> import pygame
>>> pygame.color.THECOLORS
{'maroon4': (139, 28, 98, 255), 'gold': (255, 215, 0, 255), 'dodgerblue3': (24, 116...long list of colors)